### ISSUE TITLE
A doubt in BG1Drawable::maskedImage()

### ISSUE THREAD

**Issue by AlexGuo1998** [sifteo/thundercracker#7]
Hello developer,
Firstly, thank you very much for making those sifteo cubes.
Recently, I try to start developing with your SDK. When I want to use the BG1 layer for painting, I noticed the function `maskedImage`:
`void maskedImage(const AssetImage &image, const PinnedAssetImage &key, unsigned frame = 0)`
(full function is [here](https://github.com/sifteo/thundercracker/blob/master/sdk/include/sifteo/video/bg1.h#L532))
I don't know why we have to pass both `AssetImage` and `PinnedAssetImage` to call this function. Do you know anything about it?
(Sorry for my poor English)
Many thanks,
Alex

**Comment by scanlime** [comment]
"Key" here is used as in the term "chroma key", it's a particular tile
value that's treated as transparent. The "Pinned" subtype is a bit of a
strange implementation detail; it's the same data type you usually use for
sprites.

To try and explain the implenentation detail: In its implementation, a
"pinned" image is stored consecutively in tile memory,  rather than using a
separate lookup table like a normal compressed asset. The "key" however
should just be a single tile. So you wouldn't think it matters whether that
single tile is stored contiguously in tile memory or not. But by
representing it with the "pinned" data type, you avoid having that extra
lookup table at all, and in fact the optimizing linker can even figure out
what tile index the key refers to during build rather than at runtime. The
function you linked to calls key.tile(sys.cube, 0) which will calculate the
key's tile index on the indicated cube. This is a trivial operation for
pinned images, so this compiles to very compact code. You could implement
this without pinned images, but it would generate some unnecessary data
that IIRC it wasn't good at optimizing out. So this wart ended up in the
API to lead people to do it the more efficient way, if I remember right.

-m

**Comment by AlexGuo1998** [comment]
Thanks for explaining!
Besides, I found an error in `BG1Drawable::getPanning()`: It returns the panning for `bg0`, not `bg1`.
The detail is [here](https://github.com/AlexGuo1998/thundercracker/commit/45ca4fb1cf7c1b690a90008c66d15cc90dd28ccb)
Since the SDK is no longer supported, I don't know if I should create a PR.

**Comment by scanlime** [comment]
Oh, thanks! Pretty sure I still have access to merge PRs; if not I should
set up an [un]official fork :)

-m
